CREATE USER user_b WITH PASSWORD 'literallyBillGates222';
GRANT CREATE ON DATABASE teambdb TO user_b;
GRANT CONNECT ON DATABASE teambdb TO user_b;
GRANT USAGE ON SCHEMA teamb TO user_b;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA teamb TO user_b;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO user_b;